version: '3.3'

services:
  django:
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    container_name: pizzeria_01
    command: bash -c "./manage.py migrate; ./manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - 8000:8000
    depends_on:
      - postgres
  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: postgres:10
    container_name: postgres_01
    env_file: .env
#    volumes:
#      - /home/daniel/Desktop/postgres_deleteme:/var/lib/postgresql/data
