# Generated by Django 2.0.1 on 2018-02-02 01:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pizzarecipe',
            old_name='igredient_id',
            new_name='igredient',
        ),
        migrations.RenameField(
            model_name='pizzarecipe',
            old_name='pizza_id',
            new_name='pizza',
        ),
    ]
