# Generated by Django 2.0.1 on 2018-02-02 01:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0002_auto_20180202_0124'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pizzarecipe',
            old_name='igredient',
            new_name='ingredient',
        ),
    ]
