# Generated by Django 2.0.1 on 2018-02-02 02:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0004_auto_20180202_0219'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='placeholders',
            new_name='pizzas',
        ),
    ]
