# Generated by Django 2.0.1 on 2018-02-14 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0005_auto_20180202_0235'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='customer',
        ),
        migrations.AddField(
            model_name='order',
            name='first_name',
            field=models.CharField(default='Daniel', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='last_name',
            field=models.CharField(default='Castro', max_length=150),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
