# Generated by Django 2.0.1 on 2018-02-15 00:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0006_auto_20180214_2358'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Placeholder',
            new_name='ReceiptItem',
        ),
    ]
